name: Deploy to Development
on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag to deploy (default: dev-{sha})"
        required: false
        type: string
        default: ""
      force-deploy:
        description: "Force deployment even if no changes"
        required: false
        type: boolean
        default: false

jobs:
  deploy-dev:
    name: Deploy to Development
    uses: projet-ccm2/shared-workflows/.github/workflows/nodejs-cd.yml@main
    if: github.event_name != 'pull_request'
    with:
      docker-image-name: ai-manager-api-dev
      docker-tag: ${{ github.event.inputs.image-tag || format('dev-{0}', github.sha) }}
      artifact-registry-repository: "ai-manager-docker-dev"
      environment: development
      cloud-run-service-name: ai-manager-dev
    secrets:
      GCP_SA_KEY: ${{ secrets.DEV_GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.DEV_GCP_PROJECT_ID }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
